/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model33(props) {
 
  const { nodes, materials, animations } = useGLTF('src/assets/models/yellow.glb')
  const { actions } = useAnimations(animations)
  return (
    <group  {...props} dispose={null}>
      <group name="Scene">
        <group name="low%20poly(separate-opacity)obj">
          <group name="SBH-57_low_poly004">
            <mesh
              name="SBH-57_low_poly001"
              castShadow
              receiveShadow
              geometry={nodes['SBH-57_low_poly001'].geometry}
              material={materials['Material.046']}
            />
            <group name="SBH-57_low_poly002">
              <group name="group8">
                <mesh
                  name="leftline1"
                  castShadow
                  receiveShadow
                  geometry={nodes.leftline1.geometry}
                  material={materials['Material.025']}
                  position={[-0.002, 0, 0]}
                  rotation={[-Math.PI, 0, 0]}
                  scale={-1}
                />
                <mesh
                  name="rightline1"
                  castShadow
                  receiveShadow
                  geometry={nodes.rightline1.geometry}
                  material={materials['Material.004']}
                  position={[0.002, 0, 0]}
                />
              </group>
              <mesh
                name="leftalogo"
                castShadow
                receiveShadow
                geometry={nodes.leftalogo.geometry}
                material={materials['Material.027']}
                position={[-2.622, 2.267, -1.897]}
                scale={0.996}
              />
              <mesh
                name="leftbottomline1"
                castShadow
                receiveShadow
                geometry={nodes.leftbottomline1.geometry}
                material={materials['Material.028']}
                position={[-0.005, 0.01, -0.001]}
                rotation={[-Math.PI, 0, 0]}
                scale={-0.996}
              />
              <mesh
                name="leftd50"
                castShadow
                receiveShadow
                geometry={nodes.leftd50.geometry}
                material={materials['Material.024']}
                position={[-2.289, 0.524, 2.071]}
                scale={0.996}
              />
              <mesh
                name="leftd51"
                castShadow
                receiveShadow
                geometry={nodes.leftd51.geometry}
                material={materials['Material.023']}
                position={[-1.959, 0.243, 2.66]}
                scale={0.996}
              />
              <mesh
                name="polySurface27"
                castShadow
                receiveShadow
                geometry={nodes.polySurface27.geometry}
                material={materials['Material.021']}
                position={[0, 0.01, -0.001]}
                scale={0.996}
              />
              <mesh
                name="polySurface27001"
                castShadow
                receiveShadow
                geometry={nodes.polySurface27001.geometry}
                material={materials['Material.057']}
                position={[0, 0.01, -0.001]}
                scale={0.996}
              />
              <mesh
                name="rightbottomline1"
                castShadow
                receiveShadow
                geometry={nodes.rightbottomline1.geometry}
                material={materials['Material.008']}
                position={[2.786, 0.938, 0.098]}
                scale={0.996}
              />
              <group name="transform12" />
            </group>
            <mesh
              name="SBH-57_low_poly003"
              castShadow
              receiveShadow
              geometry={nodes['SBH-57_low_poly003'].geometry}
              material={materials['Material.039']}
            />
            <mesh
              name="SBH-57_low_poly005"
              castShadow
              receiveShadow
              geometry={nodes['SBH-57_low_poly005'].geometry}
              material={materials['Material.045']}
            />
            <mesh
              name="SBH-57_low_poly006"
              castShadow
              receiveShadow
              geometry={nodes['SBH-57_low_poly006'].geometry}
              material={materials['Material.044']}
            />
            <mesh
              name="SBH-57_low_poly007"
              castShadow
              receiveShadow
              geometry={nodes['SBH-57_low_poly007'].geometry}
              material={materials['Material.047']}
            />
          </group>
        </group>
        <group name="polySurface23">
          <group name="transform11" />
        </group>
        <group name="polySurface13" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            name="leftg6"
            castShadow
            receiveShadow
            geometry={nodes.leftg6.geometry}
            material={materials['Material.055']}
            rotation={[-Math.PI, 0, 0]}
            scale={-1}
          />
          <mesh
            name="leftg6001"
            castShadow
            receiveShadow
            geometry={nodes.leftg6001.geometry}
            material={materials['Material.034']}
            rotation={[-Math.PI, 0, 0]}
            scale={-1}
          />
          <group name="polySurface40">
            <group name="group10" position={[3, 0, 0]}>
              <group name="group11">
                <mesh
                  name="leftd1"
                  castShadow
                  receiveShadow
                  geometry={nodes.leftd1.geometry}
                  material={materials['Material.019']}
                  position={[-3.025, 0, 0]}
                  rotation={[-Math.PI, 0, 0]}
                  scale={-1}
                />
                <mesh
                  name="leftg5"
                  castShadow
                  receiveShadow
                  geometry={nodes.leftg5.geometry}
                  material={materials['Material.053']}
                  position={[-3.03, 0, 0]}
                  rotation={[-Math.PI, 0, 0]}
                  scale={-1}
                />
                <mesh
                  name="leftg5001"
                  castShadow
                  receiveShadow
                  geometry={nodes.leftg5001.geometry}
                  material={materials['Material.035']}
                  position={[-3.03, 0, 0]}
                  rotation={[-Math.PI, 0, 0]}
                  scale={-1}
                />
                <mesh
                  name="rightd15"
                  castShadow
                  receiveShadow
                  geometry={nodes.rightd15.geometry}
                  material={materials['Material.018']}
                  position={[-3.025, 0, 0]}
                />
                <mesh
                  name="rightg11"
                  castShadow
                  receiveShadow
                  geometry={nodes.rightg11.geometry}
                  material={materials['Material.052']}
                  position={[-2.97, 0, 0]}
                />
                <mesh
                  name="rightg11001"
                  castShadow
                  receiveShadow
                  geometry={nodes.rightg11001.geometry}
                  material={materials['Material.033']}
                  position={[-2.97, 0, 0]}
                />
              </group>
            </group>
            <group name="transform15" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          </group>
          <mesh
            name="rightd49"
            castShadow
            receiveShadow
            geometry={nodes.rightd49.geometry}
            material={materials['Material.012']}
            position={[227.694, 225.434, -62.041]}
          />
          <mesh
            name="rightg10"
            castShadow
            receiveShadow
            geometry={nodes.rightg10.geometry}
            material={materials['Material.054']}
          />
          <mesh
            name="rightg10001"
            castShadow
            receiveShadow
            geometry={nodes.rightg10001.geometry}
            material={materials['Material.032']}
          />
          <mesh
            name="rightg31"
            castShadow
            receiveShadow
            geometry={nodes.rightg31.geometry}
            material={materials['Material.061']}
          />
          <mesh
            name="rightg4"
            castShadow
            receiveShadow
            geometry={nodes.rightg4.geometry}
            material={materials['Material.050']}
          />
          <mesh
            name="rights2"
            castShadow
            receiveShadow
            geometry={nodes.rights2.geometry}
            material={materials['Material.011']}
          />
          <mesh
            name="rights3"
            castShadow
            receiveShadow
            geometry={nodes.rights3.geometry}
            material={materials['Material.010']}
          />
          <mesh
            name="rights4"
            castShadow
            receiveShadow
            geometry={nodes.rights4.geometry}
            material={materials['Material.015']}
          />
          <mesh
            name="rights6"
            castShadow
            receiveShadow
            geometry={nodes.rights6.geometry}
            material={materials['Material.014']}
          />
          <mesh
            name="rights7"
            castShadow
            receiveShadow
            geometry={nodes.rights7.geometry}
            material={materials['Material.013']}
          />
          <mesh
            name="rights9"
            castShadow
            receiveShadow
            geometry={nodes.rights9.geometry}
            material={materials['Material.016']}
          />
        </group>
        <group name="polySurface31" rotation={[-Math.PI / 2, 0, 0]} scale={-0.01}>
          <mesh
            name="leftb9"
            castShadow
            receiveShadow
            geometry={nodes.leftb9.geometry}
            material={materials['Material.017']}
          />
          <mesh
            name="leftd36"
            castShadow
            receiveShadow
            geometry={nodes.leftd36.geometry}
            material={materials['Material.036']}
            position={[227.683, 225.434, -62.041]}
          />
          <mesh
            name="leftg3"
            castShadow
            receiveShadow
            geometry={nodes.leftg3.geometry}
            material={materials['Material.051']}
          />
          <mesh
            name="leftg31"
            castShadow
            receiveShadow
            geometry={nodes.leftg31.geometry}
            material={materials['Material.062']}
          />
          <mesh
            name="leftg4"
            castShadow
            receiveShadow
            geometry={nodes.leftg4.geometry}
            material={materials['Material.058']}
          />
          <mesh
            name="lefts1"
            castShadow
            receiveShadow
            geometry={nodes.lefts1.geometry}
            material={materials['Material.020']}
          />
          <mesh
            name="lefts2"
            castShadow
            receiveShadow
            geometry={nodes.lefts2.geometry}
            material={materials['Material.038']}
          />
          <mesh
            name="lefts3"
            castShadow
            receiveShadow
            geometry={nodes.lefts3.geometry}
            material={materials['Material.022']}
          />
        </group>
        <mesh
          name="rightg2"
          castShadow
          receiveShadow
          geometry={nodes.rightg2.geometry}
          material={materials['Material.048']}
        />
        <mesh
          name="rights1"
          castShadow
          receiveShadow
          geometry={nodes.rights1.geometry}
          material={materials['Material.037']}
        />
        <mesh
          name="leftd5"
          castShadow
          receiveShadow
          geometry={nodes.leftd5.geometry}
          material={materials['Material.005']}
        />
        <mesh
          name="leftg2"
          castShadow
          receiveShadow
          geometry={nodes.leftg2.geometry}
          material={materials['Material.049']}
          position={[0, 0, -0.006]}
          rotation={[Math.PI, 0, 0]}
          scale={-1}
        />
        <mesh
          name="tophead"
          castShadow
          receiveShadow
          geometry={nodes.tophead.geometry}
          material={materials['Material.002']}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="rightfighter"
          castShadow
          receiveShadow
          geometry={nodes.rightfighter.geometry}
          material={materials['Material.006']}
        />
        <mesh
          name="leftd1001"
          castShadow
          receiveShadow
          geometry={nodes.leftd1001.geometry}
          material={materials['Material.043']}
        />
        <mesh
          name="toprightdesign"
          castShadow
          receiveShadow
          geometry={nodes.toprightdesign.geometry}
          material={materials['Material.001']}
          position={[0.005, 0, 0]}
        />
        <mesh
          name="toprightarrow"
          castShadow
          receiveShadow
          geometry={nodes.toprightarrow.geometry}
          material={materials['Material.030']}
          position={[0, 0.002, 0]}
          rotation={[Math.PI, 0, 0]}
          scale={-1}
        />
        <mesh
          name="topleftarrow"
          castShadow
          receiveShadow
          geometry={nodes.topleftarrow.geometry}
          material={materials['Material.031']}
          position={[0, 0.002, 0]}
        />
        <mesh
          name="topleftdesign"
          castShadow
          receiveShadow
          geometry={nodes.topleftdesign.geometry}
          material={materials['Material.003']}
          position={[-0.005, 0, 0]}
          rotation={[Math.PI, 0, 0]}
          scale={-1}
        />
        <mesh
          name="leftg1"
          castShadow
          receiveShadow
          geometry={nodes.leftg1.geometry}
          material={materials['Material.041']}
        />
        <mesh
          name="backalogo"
          castShadow
          receiveShadow
          geometry={nodes.backalogo.geometry}
          material={materials['Material.029']}
        />
        <mesh
          name="rightg1"
          castShadow
          receiveShadow
          geometry={nodes.rightg1.geometry}
          material={materials['Material.040']}
        />
        <mesh
          name="backd1"
          castShadow
          receiveShadow
          geometry={nodes.backd1.geometry}
          material={materials['Material.009']}
        />
        <group name="group9" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            name="rightalogo"
            castShadow
            receiveShadow
            geometry={nodes.rightalogo.geometry}
            material={materials['Material.007']}
          />
        </group>
        <mesh
          name="leftighter"
          castShadow
          receiveShadow
          geometry={nodes.leftighter.geometry}
          material={materials['Material.026']}
        />
        <group name="rightg20" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            name="rightg40"
            castShadow
            receiveShadow
            geometry={nodes.rightg40.geometry}
            material={materials['Material.056']}
          />
        </group>
        <mesh
          name="rightd1001"
          castShadow
          receiveShadow
          geometry={nodes.rightd1001.geometry}
          material={materials['Material.059']}
          rotation={[Math.PI, 0, 0]}
          scale={-1}
        />
        <mesh
          name="rightd1002"
          castShadow
          receiveShadow
          geometry={nodes.rightd1002.geometry}
          material={materials['Material.042']}
          rotation={[Math.PI, 0, 0]}
          scale={-1}
        />
        <mesh
          name="leftd1002"
          castShadow
          receiveShadow
          geometry={nodes.leftd1002.geometry}
          material={materials['Material.060']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('src/assets/models/yellow.glb')



